### 1교시

In [10]:
import csv

f = open('./seoul_monthly_temperature_data.csv', 'r', encoding='cp949')
# f = open('./seoul_yearly_temperature_data.csv')
data = csv.reader(f)

print(data)
f.close()

<_csv.reader object at 0x0000023E29297040>

In [11]:
f = open('./seoul_monthly_temperature_data.csv', 'r', encoding='cp949')
data = csv.reader(f)

for row in data:
    print(row)

f.close()

['날짜', '지점', '평균기온(℃)', '최저기온(℃)', '최고기온(℃)']
['\t2024-08-20', '108', '31.4', '27', '35.4']
['\t2024-08-21', '108', '28.4', '26.9', '30.8']
['\t2024-08-22', '108', '28.6', '27.1', '30.3']
['\t2024-08-23', '108', '28.4', '26.4', '31.8']
['\t2024-08-24', '108', '27.6', '25.1', '30.9']
['\t2024-08-25', '108', '28.5', '24.9', '32.7']
['\t2024-08-26', '108', '28.1', '25.6', '30.6']
['\t2024-08-27', '108', '26.5', '24.6', '30.3']
['\t2024-08-28', '108', '28.2', '23', '33.2']
['\t2024-08-29', '108', '28.4', '23.4', '33.5']
['\t2024-08-30', '108', '28', '23.7', '32.9']
['\t2024-08-31', '108', '27.6', '22.6', '33']
['\t2024-09-01', '108', '27.1', '24.6', '31.6']
['\t2024-09-02', '108', '24.5', '22.2', '26.9']
['\t2024-09-03', '108', '27', '23.2', '32']
['\t2024-09-04', '108', '27.9', '23.2', '33.3']
['\t2024-09-05', '108', '26.3', '25.6', '28.8']
['\t2024-09-06', '108', '24', '23.3', '25.7']
['\t2024-09-07', '108', '26.5', '22.8', '31.3']
['\t2024-09-08', '108', '27.2', '22.6', '32.8']
['\t2024-09-09', '108', '28.5', '24.1', '34.1']
['\t2024-09-10', '108', '29.4', '25.6', '33.9']
['\t2024-09-11', '108', '29', '25.4', '34.6']
['\t2024-09-12', '108', '25.4', '24.8', '27.1']
['\t2024-09-13', '108', '25.9', '24.2', '28']
['\t2024-09-14', '108', '28', '25.2', '32.2']
['\t2024-09-15', '108', '27.5', '24.2', '32.4']
['\t2024-09-16', '108', '26.8', '21.3', '32.2']
['\t2024-09-17', '108', '28.6', '25.8', '33.2']
['\t2024-09-18', '108', '29.4', '26.5', '33.6']
['\t', '', '', '', '']

In [12]:
with open('./seoul_monthly_temperature_data.csv', 'r', encoding='cp949') as f:
    data = csv.reader(f)
    
    for row in data:
        print(row)

['날짜', '지점', '평균기온(℃)', '최저기온(℃)', '최고기온(℃)']
['\t2024-08-20', '108', '31.4', '27', '35.4']
['\t2024-08-21', '108', '28.4', '26.9', '30.8']
['\t2024-08-22', '108', '28.6', '27.1', '30.3']
['\t2024-08-23', '108', '28.4', '26.4', '31.8']
['\t2024-08-24', '108', '27.6', '25.1', '30.9']
['\t2024-08-25', '108', '28.5', '24.9', '32.7']
['\t2024-08-26', '108', '28.1', '25.6', '30.6']
['\t2024-08-27', '108', '26.5', '24.6', '30.3']
['\t2024-08-28', '108', '28.2', '23', '33.2']
['\t2024-08-29', '108', '28.4', '23.4', '33.5']
['\t2024-08-30', '108', '28', '23.7', '32.9']
['\t2024-08-31', '108', '27.6', '22.6', '33']
['\t2024-09-01', '108', '27.1', '24.6', '31.6']
['\t2024-09-02', '108', '24.5', '22.2', '26.9']
['\t2024-09-03', '108', '27', '23.2', '32']
['\t2024-09-04', '108', '27.9', '23.2', '33.3']
['\t2024-09-05', '108', '26.3', '25.6', '28.8']
['\t2024-09-06', '108', '24', '23.3', '25.7']
['\t2024-09-07', '108', '26.5', '22.8', '31.3']
['\t2024-09-08', '108', '27.2', '22.6', '32.8']
['\t2024-09-09', '108', '28.5', '24.1', '34.1']
['\t2024-09-10', '108', '29.4', '25.6', '33.9']
['\t2024-09-11', '108', '29', '25.4', '34.6']
['\t2024-09-12', '108', '25.4', '24.8', '27.1']
['\t2024-09-13', '108', '25.9', '24.2', '28']
['\t2024-09-14', '108', '28', '25.2', '32.2']
['\t2024-09-15', '108', '27.5', '24.2', '32.4']
['\t2024-09-16', '108', '26.8', '21.3', '32.2']
['\t2024-09-17', '108', '28.6', '25.8', '33.2']
['\t2024-09-18', '108', '29.4', '26.5', '33.6']
['\t', '', '', '', '']

In [13]:
f = open('./seoul_monthly_temperature_data.csv', 'r', encoding='cp949')
data = csv.reader(f)

for row in data:
    if '' in row:
        print(row)

f.close()

['\t', '', '', '', '']